const accessories = [
  {
    id: 1,
    name: "Bóng Đá Động Lực FIFA QUALITY UVI 2.05 TERRA Size 5",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 1150000,
    oldPrice: 1200000,
    thumbnail: "images/ball1.png",
    stock: 11,
    images: ["images/ball1.png"],
    desc: "Bóng nảy chuẩn, sút rất đã chân.",
  },
  {
    id: 2,
    name: "Bóng đá Động Lực FIFA Basic UBG 2.142 Victory Size 5 Xanh",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 920000,
    oldPrice: 1200000,
    thumbnail: "images/ball2.png",
    stock: 12,
    images: ["images/ball2.png"],
    desc: "Bóng nảy chuẩn, sút rất đã chân.",
  },

  {
    id: 3,
    name: "Bóng đá số 4 UCV 3.05 Terra xanh",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 350000,
    oldPrice: 500000,
    thumbnail: "images/ball3.png",
    stock: 17,
    images: ["images/ball3.png"],
    desc: "Bóng nảy chuẩn, sút rất đã chân.",
  },

  {
    id: 4,
    name: "Quả bóng đá size 4 Zocker Empire EN204",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 550000,
    oldPrice: 700000,
    thumbnail: "images/ball4.png",
    stock: 33,
    images: ["images/ball4.png"],
    desc: "“Cầm lên thấy chắc tay, chất lượng khá ổn trong tầm giá.",
  },

  {
    id: 5,
    name: "Quả bóng đá Zocker size 4 Inspire ZK4-IN204",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 450000,
    oldPrice: 700000,
    thumbnail: "images/ball5.png",
    stock: 45,
    images: ["images/ball5.png"],
    desc: "“Cầm lên thấy chắc tay, chất lượng khá ổn trong tầm giá.",
  },

  {
    id: 6,
    name: "Bóng Đá Động Lực UCV 3.05 SỐ 4",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 310000,
    oldPrice: 400000,
    thumbnail: "images/ball6.png",
    stock: 2,
    images: ["images/ball6.png"],
    desc: "“Chơi lâu không bị xì hơi, độ bền tốt.",
  },

  {
    id: 7,
    name: "Quả bóng đá size 5 Zocker Denver ZK5-D2305",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 350000,
    oldPrice: 400000,
    thumbnail: "images/ball7.png",
    stock: 11,
    images: ["images/ball7.png"],
    desc: "“Chơi lâu không bị xì hơi, độ bền tốt.",
  },

  {
    id: 8,
    name: "Bóng đá Động Lực số 5 UHV 2.151 Striker",
    type: "BALL",
    brand: "",
    _source: "access",
    price: 270000,
    oldPrice: 400000,
    thumbnail: "images/ball8.png",
    stock: 19,
    images: ["images/ball8.png"],
    desc: "“Chơi lâu không bị xì hơi, độ bền tốt.",
  },

  {
    id: 9,
    name: "Găng Tay Thủ Môn Gamicy RainBow - Xanh Chuối",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 589000,
    oldPrice: 700000,
    thumbnail: "images/gloves1.png",
    stock: 8,
    images: ["images/gloves1.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 10,
    name: "Găng Tay Thủ Môn Gamicy Mystery - Cam",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 389000,
    oldPrice: 500000,
    thumbnail: "images/gloves2.png",
    stock: 11,
    images: ["images/gloves2.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 11,
    name: "Găng tay thủ môn viper kaiwin",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 539000,
    oldPrice: 600000,
    thumbnail: "images/gloves3.png",
    stock: 23,
    images: ["images/gloves3.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 12,
    name: "Găng tay thủ môn gamicy mystery",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 539000,
    oldPrice: 600000,
    thumbnail: "images/gloves4.png",
    stock: 54,
    images: ["images/gloves4.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 13,
    name: "Găng Tay Kaiwin Master",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 239000,
    oldPrice: 300000,
    thumbnail: "images/gloves5.png",
    stock: 54,
    images: ["images/gloves5.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 14,
    name: "Găng tay thủ môn Kaiwin Artemis",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 269000,
    oldPrice: 300000,
    thumbnail: "images/gloves6.png",
    stock: 12,
    images: ["images/gloves6.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 15,
    name: "Găng tay thủ môn Zocker Dino",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 399000,
    oldPrice: 500000,
    thumbnail: "images/gloves7.png",
    stock: 42,
    images: ["images/gloves7.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },

  {
    id: 16,
    name: "Găng Tay Thủ Môn Zocker Gloves Edwin",
    type: "GLOVES",
    brand: "",
    _source: "access",
    price: 399000,
    oldPrice: 500000,
    thumbnail: "images/gloves8.png",
    stock: 15,
    images: ["images/gloves8.png"],
    desc: "“Bám bóng tốt, bắt dính tay, rất tự tin khi đổ người.",
  },
];

// 🔥 reset để chắc chắn update
localStorage.setItem("Accessories", JSON.stringify(accessories));

window.accessories = accessories;
